'use strict';
const DEMO=true,KEY='harbornest-hearth-haven-v1-' +(DEMO?'demo':'customer');
const $=s=>document.querySelector(s),app=$('#app'),dialog=$('#editor');
const escapeHTML=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const dateOK=s=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;const [y,m,d]=s.split('-').map(Number);const t=new Date(Date.UTC(2000,0,1));t.setUTCFullYear(y,m-1,d);return y>0&&m>0&&m<13&&t.getUTCFullYear()===y&&t.getUTCMonth()===m-1&&t.getUTCDate()===d};
const dateFrom=(y,m,d)=>{const t=new Date(Date.UTC(2000,0,1));t.setUTCFullYear(y,m,d);return t.toISOString().slice(0,10)};
const addDays=(s,n)=>{const [y,m,d]=s.split('-').map(Number);return dateFrom(y,m-1,d+n)};
const weekStart=s=>{const [y,m,d]=s.split('-').map(Number);return addDays(s,-((new Date(Date.UTC(y,m-1,d)).getUTCDay()+6)%7))};
const id=()=>crypto.randomUUID?.()||String(Date.now())+Math.random(),cents=s=>Math.round(Number(s)*100);
const month=()=>today().slice(0,7),money=n=>new Intl.NumberFormat(undefined,{style:'currency',currency:data.settings.currency}).format(n/100);
const labelDate=s=>dateOK(s)?new Date(s+'T12:00:00Z').toLocaleDateString(undefined,{month:'short',day:'numeric',timeZone:'UTC'}):'No date';
const prefs=()=>({name:'Our family',theme:'mint',customColor:'#317861',font:'system',density:'comfortable',cards:'soft',contrast:'normal',currency:'USD',monthlyBudget:0});
const kinds=['events','tasks','meals','groceries','transactions','bills','savings','goals','habits','habitLogs','billPayments','chores','contacts','notes','kids','school','care','maintenance','documents','recipes','medical','medications','trips','packing','memories','traditions','rewards'];
const blank=()=>({version:2,settings:prefs(),...Object.fromEntries(kinds.map(k=>[k,[]]))});
const fields={
 events:[['title','Event','text',1],['date','Date','date',1],['time','Time','time'],['person','Family member','text'],['category','Category','select:Family|School|Health|Work|Fun'],['note','Details','textarea']],
 tasks:[['title','Task','text',1],['date','Due date','date',1],['person','Who will do it?','text'],['priority','Priority','select:Normal|Important|Flexible']],
 meals:[['date','Day','date',1],['meal','Meal idea','text',1],['note','Preparation note','textarea']],
 groceries:[['title','Grocery item','text',1],['category','Aisle / category','text']],
 transactions:[['title','Description','text',1],['date','Date','date',1],['kind','Type','select:expense|income',1],['category','Category','text'],['amount','Amount','money',1]],
 bills:[['title','Bill or subscription','text',1],['due','Next due date','date',1],['amount','Amount','money',1],['cycle','Repeats','select:once|monthly'],['category','Type','select:Bill|Subscription']],
 savings:[['title','Deposit note','text',1],['date','Date','date',1],['goalId','Savings goal','goal'],['amount','Amount saved','money',1]],
 goals:[['title','Goal','text',1],['category','Type','select:Family|Personal|Savings'],['target','Target amount or units','quantity',1],['progress','Starting progress','quantity'],['due','Target date','date']],
 habits:[['title','Habit','text',1],['person','For whom?','text'],['frequency','Target days per week','days',1]],
 chores:[['title','Chore','text',1],['date','Date','date',1],['person','Who will do it?','text']],
 contacts:[['name','Name','text',1],['phone','Phone number','tel'],['detail','Details','text'],['emergency','Emergency contact','check']],
 notes:[['title','Title','text',1],['body','Note','textarea']],
 kids:[['title','Activity','text',1],['date','Date','date',1],['time','Time','time'],['person','Child','text'],['note','Location / kit','text']],
 school:[['title','School item','text',1],['date','Date','date',1],['person','Child','text'],['type','Type','select:Homework|Event|Deadline|Term'],['note','Details','textarea']],
 care:[['title','Self-care activity','text',1],['date','Date','date',1],['minutes','Minutes','minutes'],['note','Reflection','textarea']],
 maintenance:[['title','Home maintenance job','text',1],['date','Next due date','date',1],['person','Owner / vendor','text'],['note','Notes','textarea']],
 recipes:[['title','Recipe name','text',1],['category','Type','select:Breakfast|Lunch|Dinner|Snack'],['ingredients','Ingredients, one per line','textarea'],['method','Method','textarea'],['minutes','Preparation minutes','minutes']],
 medical:[['title','Appointment / record','text',1],['date','Date','date',1],['person','Family member','text'],['provider','Clinic / provider','text'],['detail','Notes (avoid sensitive IDs)','textarea']],
 medications:[['title','Medication name','text',1],['person','Family member','text'],['dose','Dose as written on label','text'],['schedule','Schedule','text'],['refill','Refill date','date'],['note','Notes','textarea']],
 trips:[['title','Trip or celebration','text',1],['date','Start date','date',1],['end','End date','date'],['destination','Destination / venue','text'],['budget','Budget','money'],['note','Itinerary / details','textarea']],
 packing:[['title','Packing item','text',1],['trip','Trip name','text'],['person','For whom?','text']],
 memories:[['title','Memory or milestone','text',1],['date','Date','date',1],['person','Family member','text'],['note','What happened?','textarea']],
 traditions:[['title','Family tradition','text',1],['date','Next date','date'],['note','How you celebrate','textarea']],
 rewards:[['title','Reward / achievement','text',1],['person','Child','text',1],['target','Points needed','quantity',1],['earned','Points earned','quantity'],['note','How points are earned','textarea']],
 documents:[['title','Document name','text',1],['category','Category','text'],['location','Where it is stored','text'],['due','Renewal / expiry date','date'],['note','Reminder note','textarea']]
};
const toggleKinds=new Set(['tasks','groceries','bills','chores','school','care','maintenance','packing']);
function migrate(raw){if(!raw||!Array.isArray(raw.events))return null;const s=blank();if(raw.version!==1&&raw.version!==2)return null;for(const k of kinds)if(!['habitLogs','billPayments'].includes(k)&&Array.isArray(raw[k]))s[k]=raw[k];s.settings={...prefs(),...(raw.settings||{})};if(Array.isArray(raw.habitLogs))s.habitLogs=raw.habitLogs;if(Array.isArray(raw.billPayments))s.billPayments=raw.billPayments;if(raw.version===1){for(const b of s.bills){b.cycle='once';b.category='Bill'}for(const e of s.events)e.category='Family';for(const t of s.tasks)t.priority='Normal';s.version=2}return s}
function valid(raw){const x=migrate(raw);if(!x)return false;const s=x.settings;if(!['USD','GBP','EUR','CAD','AUD','PKR'].includes(s.currency)||!['mint','peach','lilac','blue','custom'].includes(s.theme)||!/^#[0-9a-f]{6}$/i.test(s.customColor)||typeof s.name!=='string'||s.name.length>45||!Number.isSafeInteger(s.monthlyBudget)||s.monthlyBudget<0||s.monthlyBudget>100000000000)return false;
 const ids=new Set();for(const k of kinds){if(!Array.isArray(x[k])||x[k].length>20000)return false;for(const r of x[k]){if(!r||typeof r.id!=='string'||!r.id||ids.has(r.id))return false;ids.add(r.id);if(k==='habitLogs'){if(typeof r.habitId!=='string'||!dateOK(r.date))return false;continue}if(k==='billPayments'){if(typeof r.billId!=='string'||!/^\d{4}-\d{2}$/.test(r.month)||!dateOK(r.month+'-01'))return false;continue}for(const [f,,type,required] of fields[k]){const v=r[f];if(required&&(v==null||v===''))return false;if(v==null)continue;if(type==='money'||['quantity','minutes','days'].includes(type)){if(!Number.isSafeInteger(v)||v<0||v>100000000000)return false}else if(type==='check'){if(typeof v!=='boolean')return false}else if(typeof v!=='string'||v.length>2000||type==='date'&&v&&!dateOK(v))return false}if(toggleKinds.has(k)&&typeof r.done!=='boolean'&&typeof r.paid!=='boolean')return false}}return true}
function sample(){const s=blank(),t=today(),w=weekStart(t),later=n=>addDays(t,n),rec=(k,v)=>s[k].push({id:id(),...v});s.settings.name='The Ellis family';s.settings.monthlyBudget=230000;
 rec('events',{title:'Family picnic',date:later(4),time:'12:00',person:'Everyone',category:'Fun',note:'Bring blankets'});rec('events',{title:'Dentist visit',date:later(2),time:'10:00',person:'Leo',category:'Health',note:''});
 rec('tasks',{title:'Return library books',date:t,person:'Maya',priority:'Important',done:false});rec('tasks',{title:'Book haircut',date:later(1),person:'Leo',priority:'Normal',done:true});
 rec('meals',{date:w,meal:'Vegetable pasta',note:'Save leftovers'});rec('meals',{date:addDays(w,1),meal:'Rice bowls',note:''});
 rec('groceries',{title:'Tomatoes',category:'Produce',done:false});rec('groceries',{title:'Rice',category:'Pantry',done:true});
 rec('transactions',{title:'Payday',date:t,kind:'income',category:'Income',amount:230000});rec('transactions',{title:'Groceries',date:t,kind:'expense',category:'Food',amount:4850});
 rec('bills',{title:'Internet',due:later(5),amount:4200,cycle:'monthly',category:'Subscription',paid:false});
 const goal=id();s.goals.push({id:goal,title:'Holiday fund',category:'Savings',target:1000,progress:150,due:later(120)});rec('savings',{title:'September deposit',date:t,goalId:goal,amount:10000});
 const habit=id();s.habits.push({id:habit,title:'Read together',person:'Everyone',frequency:5});s.habitLogs.push({id:id(),habitId:habit,date:t});
 rec('chores',{title:'Laundry',date:t,person:'You',done:false});rec('contacts',{name:'School office',phone:'555-0140',detail:'Front desk',emergency:true});rec('notes',{title:'Weekend idea',body:'Visit the botanical garden.'});
 rec('kids',{title:'Swimming class',date:later(3),time:'15:00',person:'Maya',note:'Pack goggles'});rec('school',{title:'Library reading log',date:later(2),person:'Leo',type:'Homework',note:'Sign reading log',done:false});
 rec('care',{title:'Evening walk',date:t,minutes:20,note:'Fresh air',done:true});rec('maintenance',{title:'Check smoke alarms',date:later(14),person:'You',note:'Replace batteries if needed',done:false});rec('recipes',{title:'Roasted vegetable bowls',category:'Dinner',ingredients:'Rice\nCarrots\nChickpeas',method:'Roast vegetables and serve over rice.',minutes:35});rec('medical',{title:'Annual checkup',date:later(8),person:'Maya',provider:'Family clinic',detail:'Bring questions.'});rec('medications',{title:'Vitamin supplement',person:'Leo',dose:'As directed',schedule:'Breakfast',refill:later(22),note:'Sample only'});rec('trips',{title:'Coastal weekend',date:later(35),end:later(37),destination:'Beach town',budget:35000,note:'Check weather before leaving'});rec('packing',{title:'Sunscreen',trip:'Coastal weekend',person:'Everyone',done:false});rec('memories',{title:'First bike ride',date:later(-7),person:'Leo',note:'We practiced at the park.'});rec('traditions',{title:'Sunday pancake breakfast',date:later(6),note:'Everyone helps with toppings.'});rec('rewards',{title:'Library visit',person:'Leo',target:10,earned:4,note:'One point per reading session'});
 rec('documents',{title:'School insurance card',category:'School',location:'Blue folder at home',due:later(80),note:'Metadata only; no files stored'});return s}
function load(){try{const raw=JSON.parse(localStorage.getItem(KEY));return valid(raw)?migrate(raw):DEMO?sample():blank()}catch{return DEMO?sample():blank()}}
let data=load(),view='dashboard',mode='day',selected=today(),search='',modal=null,previousFocus=null,chartPeriod='month';
const navigation=[['dashboard','Overview','⌂'],['planner','Planner','▦'],['calendar','Calendar','□'],['family','Family','♧'],['meals','Meals','◒'],['lists','Lists','☑'],['money','Money','◫'],['growth','Growth','◇'],['wellness','Wellness','✿'],['home','Home','⌑'],['reports','Reports','◉'],['health','Health','♡'],['recipes','Recipes','♨'],['travel','Travel','✈'],['memories','Memories','✿'],['rewards','Rewards','★'],['settings','Customize','✦']];
const heading={dashboard:'A little room to breathe',planner:'Make space for the day',calendar:'A month for everyone',family:'Your family, together',meals:'What’s for dinner?',lists:'The little things, handled',money:'A clearer picture',growth:'Small steps add up',wellness:'A moment for you',home:'Keep home in order',reports:'See the whole picture',health:'Health, in one place',recipes:'Recipes you love',travel:'Trips worth remembering',memories:'Your family story',rewards:'Celebrate little wins',settings:'Make this yours'};
const subtitles={dashboard:'Your next steps, all in one gentle overview.',planner:'Daily, weekly and monthly plans in one place.',calendar:'A shared family view in this browser.',family:'Schedules, school life and activities.',meals:'Simple food plans and a grocery list.',lists:'Check off the little things.',money:'Recorded income, expenses, bills and savings.',growth:'Goals and habits that you can actually track.',wellness:'A little space for self-care.',home:'Maintenance, important document references and contacts.',reports:'Your own records, shown clearly.',health:'Appointments and medication reference notes.',recipes:'Save recipes and add ingredients to groceries.',travel:'Trips, celebrations, itineraries and packing.',memories:'Milestones and traditions to look back on.',rewards:'A simple points tracker for kids.',settings:'Make the planner comfortable and keep a backup.'};
function save(){try{localStorage.setItem(KEY,JSON.stringify(data));$('#saveStatus').textContent='Saved on this device'}catch{$('#saveStatus').textContent='Storage full — download a backup'}}
function colorShade(hex){const n=parseInt(hex.slice(1),16),rgb=[n>>16,n>>8&255,n&255];const lum=c=>{const v=c/255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4};let scale=1;while(scale>0&&(.2126*lum(rgb[0]*scale)+.7152*lum(rgb[1]*scale)+.0722*lum(rgb[2]*scale))>.15)scale-=.025;return '#'+rgb.map(v=>Math.round(v*Math.max(0,scale)).toString(16).padStart(2,'0')).join('')}
function apply(){const s=data.settings,root=document.documentElement;for(const k of ['theme','font','density','cards','contrast'])root.dataset[k]=s[k];root.style.setProperty('--custom-accent',colorShade(s.customColor));root.style.setProperty('--custom-soft',s.customColor+'2c');document.title=(s.name||'Hearth Haven')+' · Family hub'}
function shell(){app.innerHTML=`<aside class="sidebar"><div class="brand"><span class="brand-mark">✦</span><div><strong>Hearth Haven</strong><small>by HarborNestDigital</small></div></div><div class="side-caption">YOUR FAMILY SPACE</div><nav aria-label="Main navigation">${navigation.map(([v,l,i])=>`<button data-view="${v}" class="nav-button"><span aria-hidden="true">${i}</span>${l}</button>`).join('')}</nav><div class="side-foot">One family, one calmer place.</div></aside><div class="main-shell"><header class="topbar"><div class="top-brand">✦ <strong>Hearth Haven</strong></div><span id="saveStatus" role="status">Saved on this device</span></header><main id="main" tabindex="-1"></main></div><nav class="mobile-nav" aria-label="Mobile navigation">${navigation.map(([v,l,i])=>`<button data-view="${v}" class="nav-button"><span aria-hidden="true">${i}</span><small>${l}</small></button>`).join('')}</nav>`;apply();render()}
const card=(title,body,extra='')=>`<section class="card ${extra}"><h2>${title}</h2>${body}</section>`;
const empty=(k)=>`<div class="empty"><span aria-hidden="true">✳</span><p>Nothing here yet. Begin with one small entry.</p><button class="button ghost" data-add="${k}">+ Add one</button></div>`;
const actions=(k,r)=>`<div class="row-actions"><button class="small-action" data-edit="${k}:${escapeHTML(r.id)}" aria-label="Edit ${escapeHTML(r.title||r.name||r.meal||'entry')}">Edit</button><button class="small-action danger" data-delete="${k}:${escapeHTML(r.id)}" aria-label="Delete ${escapeHTML(r.title||r.name||r.meal||'entry')}">Delete</button></div>`;
const list=(k,arr,describe)=>arr.length?`<div class="rows">${arr.map(r=>`<article class="entry"><div class="entry-main">${describe(r)}</div>${actions(k,r)}</article>`).join('')}</div>`:empty(k);
const sorted=arr=>[...arr].sort((a,b)=>(a.date||a.due||'').localeCompare(b.date||b.due||''));
const billPaid=(r,m)=>r.cycle==='monthly'?data.billPayments.some(p=>p.billId===r.id&&p.month===m):r.paid;
const button=k=>`<button class="button primary inline-add" data-add="${k}">+ Add ${{kids:'activity',care:'self-care',groceries:'grocery item',school:'school item',maintenance:'maintenance job',transactions:'transaction',documents:'document reference',savings:'deposit'}[k]||k.slice(0,-1)}</button>`;
const check=(k,r,text,meta)=>`<label class="check-row"><input type="checkbox" data-check="${k}:${escapeHTML(r.id)}" ${r.done||r.paid?'checked':''}><span class="${r.done||r.paid?'completed':''}"><strong>${escapeHTML(text)}</strong><small>${escapeHTML(meta)}</small></span></label>`;
const header=()=>`<div class="page-header"><div><span class="eyebrow">${escapeHTML(data.settings.name)} · ${labelDate(selected)}</span><h1>${heading[view]}</h1><p>${subtitles[view]}</p></div><span class="header-doodle" aria-hidden="true">✺</span></div>`;
function setSelected(n){selected=addDays(selected,n);render()}
function shiftMonth(n){const [y,m]=selected.split('-').map(Number),day=Number(selected.slice(-2)),first=dateFrom(y,m-1+n,1),[ny,nm]=first.split('-').map(Number),last=new Date(Date.UTC(ny,nm,0)).getUTCDate();selected=dateFrom(ny,nm-1,Math.min(day,last));render()}
const dateControls=(range=mode)=>`<div class="toolbar"><button class="icon-button" ${range==='month'?'data-shift-month="-1"':'data-offset="'+(range==='week'?-7:-1)+'"'} aria-label="Previous period">‹</button><h2>${range==='month'?new Date(selected+'T12:00:00Z').toLocaleDateString(undefined,{month:'long',year:'numeric',timeZone:'UTC'}):range==='week'?'Week of '+labelDate(weekStart(selected)):labelDate(selected)}</h2><button class="icon-button" ${range==='month'?'data-shift-month="1"':'data-offset="'+(range==='week'?7:1)+'"'} aria-label="Next period">›</button><button class="button ghost" data-today>Today</button></div>`;
function dashboard(){
 const t=today(),upcoming=sorted([
  ...data.events.map(r=>({...r,kind:'events'})),...data.kids.map(r=>({...r,kind:'kids'})),...data.school.map(r=>({...r,kind:'school'}))
 ].filter(r=>r.date>=t)).slice(0,4);
 const pending=data.tasks.filter(r=>!r.done&&r.date<=t),bills=data.bills.filter(r=>!r.paid).length;
 const schedule=upcoming.length?upcoming.map(r=>`<article class="entry"><span class="date-chip">${labelDate(r.date)}</span><div class="entry-main"><strong>${escapeHTML(r.title)}</strong><small>${escapeHTML(r.person||'Family')}</small></div>${actions(r.kind,r)}</article>`).join(''):empty('events');
 return `<div class="welcome"><div><span class="eyebrow">YOUR FAMILY, IN FOCUS</span><h2>Today feels lighter when it’s all here.</h2><p>Choose one useful next step. The rest can wait its turn.</p><button class="button white" data-add="tasks">+ Add a task</button></div><div class="welcome-art" aria-hidden="true">✿</div></div><div class="stats"><div class="stat"><span>Needs attention</span><strong>${pending.length}</strong><small>Tasks due today or earlier</small></div><div class="stat"><span>Upcoming plans</span><strong>${upcoming.length}</strong><small>Events, kids and school</small></div><div class="stat"><span>Unpaid bills</span><strong>${bills}</strong><small>Still to mark paid</small></div></div><div class="two-col">${card('Coming up',schedule)}${card('One thing at a time',button('tasks')+list('tasks',pending.slice(0,5),r=>check('tasks',r,r.title,`${labelDate(r.date)} · ${r.person||'Family'}`)))}</div>${card('This month at a glance',analyticsSummary(),'under-card')}`;
}
function calendarGrid(m){const [y,mo]=m.split('-').map(Number),first=(new Date(Date.UTC(y,mo-1,1)).getUTCDay()+6)%7,days=new Date(Date.UTC(y,mo,0)).getUTCDate(),count=Math.ceil((first+days)/7)*7;return `<div class="calendar" role="grid" aria-label="Family calendar for ${m}">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(v=>`<div class="weekday">${v}</div>`).join('')}${Array.from({length:count},(_,i)=>{const iso=dateFrom(y,mo-1,i-first+1),entries=[...data.events.map(r=>({...r,kind:'events'})),...data.kids.map(r=>({...r,kind:'kids'})),...data.school.map(r=>({...r,kind:'school'}))].filter(r=>r.date===iso);return `<div class="calendar-day ${iso.slice(0,7)===m?'':'muted'} ${iso===today()?'current':''}"><span>${Number(iso.slice(-2))}</span>${entries.slice(0,2).map(r=>`<button data-edit="${r.kind}:${escapeHTML(r.id)}" title="${escapeHTML(r.title)}">${escapeHTML(r.title)}</button>`).join('')}${entries.length>2?`<small>+${entries.length-2} more</small>`:''}</div>`}).join('')}</div>`}
function daily(){const d=selected,e=sorted([...data.events.map(x=>({...x,kind:'events'})),...data.kids.map(x=>({...x,kind:'kids'})),...data.school.map(x=>({...x,kind:'school'}))].filter(x=>x.date===d));return `<div class="two-col">${card('Your schedule',button('events')+(e.length?e.map(r=>`<article class="entry"><span class="date-chip">${escapeHTML(r.time||'All day')}</span><div class="entry-main"><strong>${escapeHTML(r.title)}</strong><small>${escapeHTML(r.person||'Family')}</small></div>${actions(r.kind,r)}</article>`).join(''):empty('events')))}${card('Daily priorities',button('tasks')+list('tasks',data.tasks.filter(x=>x.date===d),r=>check('tasks',r,r.title,r.person||'Family')))}</div>`}
function weekly(){const w=weekStart(selected);return `<div class="week-grid">${Array.from({length:7},(_,i)=>{const d=addDays(w,i),day=new Date(d+'T12:00:00Z').toLocaleDateString(undefined,{weekday:'long',timeZone:'UTC'}),e=[...data.events,...data.kids,...data.school].filter(x=>x.date===d),t=data.tasks.filter(x=>x.date===d);return `<section class="meal-day"><span class="eyebrow">${day} · ${labelDate(d)}</span>${[...e,...t].map(r=>`<p class="week-entry">${escapeHTML(r.title)}</p>`).join('')||'<p>Room for a plan</p>'}<button class="text-button" data-add="events" data-date="${d}">+ Event</button></section>`}).join('')}</div>`}
function planner(){return `<div class="tabs" role="group" aria-label="Planner time range">${['day','week','month'].map(v=>`<button data-mode="${v}" class="${mode===v?'active':''}" aria-pressed="${mode===v}">${v[0].toUpperCase()+v.slice(1)}</button>`).join('')}</div>${dateControls()}${mode==='day'?daily():mode==='week'?weekly():calendarGrid(selected.slice(0,7))}`}
function calendar(){return `${dateControls('month')}${calendarGrid(selected.slice(0,7))}<p class="disclaimer">This calendar combines family events, children’s activities and school entries saved in this browser. It does not synchronize live with other devices.</p>`}
function family(){const schedule=sorted(data.events.filter(r=>r.date>=today())).slice(0,12);return `<div class="two-col">${card('Family schedule',button('events')+list('events',schedule,r=>`<strong>${escapeHTML(r.title)}</strong><small>${labelDate(r.date)} ${escapeHTML(r.time)} · ${escapeHTML(r.person||'Family')} · ${escapeHTML(r.category||'Family')}</small>`))}${card('Kids activities',button('kids')+list('kids',sorted(data.kids),r=>`<strong>${escapeHTML(r.title)}</strong><small>${labelDate(r.date)} ${escapeHTML(r.time)} · ${escapeHTML(r.person)}</small>`))}${card('School planner',button('school')+list('school',sorted(data.school),r=>check('school',r,r.title,`${labelDate(r.date)} · ${r.person} · ${r.type}`)),'wide')}</div><p class="disclaimer">The calendar is shared within this browser profile. Other devices do not update automatically; use a backup to transfer a snapshot.</p>`}
function meals(){const w=weekStart(selected);return `${dateControls('week')}<div class="meal-grid">${Array.from({length:7},(_,i)=>{const d=addDays(w,i),label=new Date(d+'T12:00:00Z').toLocaleDateString(undefined,{weekday:'long',timeZone:'UTC'});return `<section class="meal-day"><span class="eyebrow">${label} · ${labelDate(d)}</span>${data.meals.filter(r=>r.date===d).map(r=>`<div class="meal-item"><strong>${escapeHTML(r.meal)}</strong><small>${escapeHTML(r.note)}</small>${actions('meals',r)}</div>`).join('')||'<p>Room for a plan</p>'}<button class="text-button" data-add="meals" data-date="${d}">+ Add meal</button></section>`}).join('')}</div>${card('Groceries to pick up',button('groceries')+list('groceries',data.groceries.filter(r=>!r.done),r=>check('groceries',r,r.title,r.category)),'under-card')}`}
function listsView(){return `<div class="two-col">${card('Family tasks',button('tasks')+list('tasks',sorted(data.tasks),r=>check('tasks',r,r.title,`${labelDate(r.date)} · ${r.person||'Family'}`)))}${card('Grocery list',button('groceries')+list('groceries',data.groceries,r=>check('groceries',r,r.title,r.category)))}</div>`}
function billDue(r,m){if(r.cycle==='monthly'&&m<r.due.slice(0,7))return null;if(r.cycle!=='monthly')return r.due.slice(0,7)===m?r.due:null;const [y,mo]=m.split('-').map(Number),day=Number(r.due.slice(-2)),last=new Date(Date.UTC(y,mo,0)).getUTCDate();return m+'-'+String(Math.min(day,last)).padStart(2,'0')}
function moneyView(){
 const m=selected.slice(0,7),tx=data.transactions.filter(r=>r.date.startsWith(m));
 const income=tx.filter(r=>r.kind==='income').reduce((a,r)=>a+r.amount,0);
 const spent=tx.filter(r=>r.kind==='expense').reduce((a,r)=>a+r.amount,0),budget=data.settings.monthlyBudget;
 const expenses=card('Budget & expenses',button('transactions')+list('transactions',sorted(tx).reverse(),r=>`<strong>${escapeHTML(r.title)}</strong><small>${labelDate(r.date)} · ${escapeHTML(r.category)} · ${escapeHTML(r.kind)}</small><b>${money(r.amount)}</b>`));
 const due=data.bills.map(r=>({...r,displayDue:billDue(r,m),paid:billPaid(r,m)})).filter(r=>r.displayDue);
 const bills=card('Bills & subscriptions',button('bills')+list('bills',due,r=>check('bills',r,r.title,`${labelDate(r.displayDue)} · ${money(r.amount)} · ${r.cycle}`)));
 const savings=card('Savings tracker',button('savings')+list('savings',data.savings,r=>`<strong>${escapeHTML(r.title)}</strong><small>${labelDate(r.date)} · ${escapeHTML(data.goals.find(g=>g.id===r.goalId)?.title||'General savings')}</small><b>${money(r.amount)}</b>`),'under-card');
 return `${dateControls('month')}<div class="stats"><div class="stat"><span>Income recorded</span><strong>${money(income)}</strong></div><div class="stat"><span>Expenses recorded</span><strong>${money(spent)}</strong></div><div class="stat"><span>Budget remaining</span><strong>${budget?money(budget-spent):'Set a budget'}</strong><small>${budget?'Budget − recorded expenses':'In Customize'}</small></div></div><div class="two-col">${expenses}${bills}</div>${savings}<p class="disclaimer">Money shows entries you add, not a connected bank balance. Savings deposits are tracked separately and do not automatically reduce expenses.</p>`;
}
function goalValue(g){return g.progress+data.savings.filter(s=>s.goalId===g.id).reduce((a,r)=>a+r.amount/100,0)}
const ring=(percent,text)=>`<div class="ring" style="--progress:${Math.min(100,Math.max(0,percent))}%" role="img" aria-label="${escapeHTML(text)}: ${Math.round(percent)} percent"><span>${Math.round(percent)}%</span></div>`;
function growth(){
 const t=today(),w=weekStart(t);
 const goals=card('Goals & savings',button('goals')+list('goals',data.goals,r=>`<div class="goal-entry">${ring(r.target?goalValue(r)/r.target*100:0,r.title)}<span><strong>${escapeHTML(r.title)}</strong><small>${r.category==='Savings'?money(Math.round(goalValue(r)*100))+' of '+money(r.target*100):goalValue(r)+' of '+r.target+' units'}</small></span></div>`));
 const habitEntries=data.habits.map(r=>{const count=data.habitLogs.filter(l=>l.habitId===r.id&&l.date>=w&&l.date<=addDays(w,6)).length,checked=data.habitLogs.some(l=>l.habitId===r.id&&l.date===t);return `<article class="entry"><div class="entry-main"><strong>${escapeHTML(r.title)}</strong><small>${escapeHTML(r.person)} · ${count} of ${r.frequency} target days this week</small><button class="button ghost" data-habit="${escapeHTML(r.id)}">${checked?'✓ Done today':'Mark today done'}</button></div>${actions('habits',r)}</article>`}).join('');
 const habits=card('Habits',button('habits')+(data.habits.length?habitEntries:empty('habits')));
 return `<div class="two-col">${goals}${habits}</div>`;
}
function wellness(){const w=weekStart(selected);return `${dateControls('week')}<div class="two-col">${card('Self-care moments',button('care')+list('care',sorted(data.care),r=>check('care',r,r.title,`${labelDate(r.date)} · ${r.minutes||0} min · ${r.note||''}`)))}${card('This week',`<p>Time you recorded for yourself: <strong>${data.care.filter(r=>r.date>=w&&r.date<=addDays(w,6)&&r.done).reduce((a,r)=>a+r.minutes,0)} minutes</strong></p><p>Try a small, repeatable pause. Your time matters, too.</p>`)}</div>`}
function home(){return `<div class="two-col">${card('Home maintenance',button('maintenance')+list('maintenance',sorted(data.maintenance),r=>check('maintenance',r,r.title,`${labelDate(r.date)} · ${r.person||'Home'}`)))}${card('Emergency contacts',button('contacts')+list('contacts',data.contacts.filter(r=>r.emergency),r=>`<strong>${escapeHTML(r.name)}</strong><small>${escapeHTML(r.phone)} · ${escapeHTML(r.detail)}</small>`))}${card('Other contacts',list('contacts',data.contacts.filter(r=>!r.emergency),r=>`<strong>${escapeHTML(r.name)}</strong><small>${escapeHTML(r.phone)} · ${escapeHTML(r.detail)}</small>`))}${card('Important documents · references only',button('documents')+list('documents',data.documents,r=>`<strong>${escapeHTML(r.title)}</strong><small>${escapeHTML(r.category)} · ${escapeHTML(r.location)}${r.due?' · Renewal '+labelDate(r.due):''}</small>`))}${card('Notes',button('notes')+list('notes',data.notes,r=>`<strong>${escapeHTML(r.title)}</strong><small>${escapeHTML(r.body)}</small>`),'wide')}</div><p class="disclaimer">Document entries hold names, locations and dates only. No files are uploaded. Avoid passwords and sensitive IDs; local browser storage is not encrypted by this planner.</p>`}
function metricSeries(){const end=selected.slice(0,7),[year,mo]=end.split('-').map(Number);return Array.from({length:chartPeriod},(_,i)=>{const m=dateFrom(year,mo-chartPeriod+i,1).slice(0,7),income=data.transactions.filter(r=>r.date.startsWith(m)&&r.kind==='income').reduce((a,r)=>a+r.amount,0),spend=data.transactions.filter(r=>r.date.startsWith(m)&&r.kind==='expense').reduce((a,r)=>a+r.amount,0),done=data.tasks.filter(r=>r.date.startsWith(m)&&r.done).length;return{m,income,spend,done}})}
function lineChart(series){
 const max=Math.max(1,...series.flatMap(x=>[x.income,x.spend])),span=540,step=series.length>1?span/(series.length-1):span;
 const px=i=>38+i*step,path=k=>series.map((x,i)=>`${i?'L':'M'} ${px(i)} ${170-x[k]/max*140}`).join(' ');
 return `<div class="tabs" role="group" aria-label="Chart date range"><button data-chart-range="6" class="${chartPeriod===6?'active':''}" aria-pressed="${chartPeriod===6}">6 months</button><button data-chart-range="12" class="${chartPeriod===12?'active':''}" aria-pressed="${chartPeriod===12}">12 months</button></div><svg viewBox="0 0 620 210" class="chart" role="img" aria-label="Monthly recorded income and expenses line chart"><title>Monthly recorded income and expenses</title><line x1="34" y1="175" x2="585" y2="175" stroke="var(--line)"/><path d="${path('income')}" fill="none" stroke="var(--accent)" stroke-width="4"/><path d="${path('spend')}" fill="none" stroke="#9c4b3c" stroke-width="4"/>${series.map((x,i)=>`<g><circle cx="${px(i)}" cy="${170-x.income/max*140}" r="7" fill="var(--accent)"><title>${x.m}: income ${money(x.income)}</title></circle><circle cx="${px(i)}" cy="${170-x.spend/max*140}" r="7" fill="#9c4b3c"><title>${x.m}: spending ${money(x.spend)}</title></circle><text x="${px(i)-17}" y="200" font-size="${series.length>6?9:12}" fill="var(--muted)">${x.m.slice(2)}</text></g>`).join('')}</svg><p class="legend">● Income &nbsp; <span>● Spending</span></p>`;
}
function donut(parts){const total=parts.reduce((a,r)=>a+r.value,0),colors=['var(--accent)','#e5a483','#a995d1','#e5be63','#7aafcf'],offset=parts.reduce((acc,r,i)=>{acc.push(parts.slice(0,i).reduce((a,p)=>a+p.value,0));return acc},[]);return `<svg class="donut" viewBox="0 0 180 180" role="img" aria-label="Family time distribution by event category"><title>Family time distribution</title><circle cx="90" cy="90" r="62" fill="none" stroke="var(--line)" stroke-width="26"/>${total?parts.map((r,i)=>`<circle cx="90" cy="90" r="62" fill="none" stroke="${colors[i%colors.length]}" stroke-width="26" stroke-dasharray="${r.value/total*389.56} 389.56" stroke-dashoffset="${-offset[i]/total*389.56}" transform="rotate(-90 90 90)"><title>${escapeHTML(r.name)}: ${r.value} events</title></circle>`).join(''):''}<text x="90" y="97" text-anchor="middle" font-size="23" fill="var(--ink)">${total}</text></svg><div class="donut-key">${parts.map((r,i)=>`<span style="--key-color:${colors[i%colors.length]}">${escapeHTML(r.name)}: ${r.value}</span>`).join('')}</div>`}
function analyticsSummary(){const m=selected.slice(0,7),tx=data.transactions.filter(r=>r.date.startsWith(m)),spent=tx.filter(r=>r.kind==='expense').reduce((a,r)=>a+r.amount,0),budget=data.settings.monthlyBudget,done=data.tasks.filter(r=>r.date.startsWith(m)&&r.done).length,all=data.tasks.filter(r=>r.date.startsWith(m)).length;return `<div class="summary-pills"><span>Tasks completed <b>${done}/${all}</b></span><span>Monthly spending <b>${money(spent)}</b></span><span>Budget used <b>${budget?Math.round(spent/budget*100)+'%':'No budget set'}</b></span></div>`}
function reports(){const series=metricSeries(),m=selected.slice(0,7),tasks=data.tasks.filter(r=>r.date.startsWith(m)),done=tasks.filter(r=>r.done).length,habitTarget=data.habits.reduce((a,r)=>a+r.frequency,0),habitActual=data.habitLogs.filter(r=>r.date>=weekStart(selected)&&r.date<=addDays(weekStart(selected),6)).length,events=[...data.events,...data.kids,...data.school].filter(r=>r.date.startsWith(m)),categories=['Family','School','Health','Work','Fun'].map(name=>({name,value:events.filter(r=>r.category===name||r.type===name||!r.category&&name==='Family').length})).filter(r=>r.value),expenses=data.transactions.filter(r=>r.date.startsWith(m)&&r.kind==='expense'),total=expenses.reduce((a,r)=>a+r.amount,0);return `${dateControls('month')}<div class="report-grid">${card('Budget analytics · six months',lineChart(series))}${card('Family time distribution',donut(categories))}${card('Productivity report',`${ring(tasks.length?done/tasks.length*100:0,'Monthly task completion')}<p>${done} of ${tasks.length} tasks completed this month.</p>`)}${card('Habit statistics',`${ring(habitTarget?habitActual/habitTarget*100:0,'Weekly habit target')}<p>${habitActual} logged days toward ${habitTarget} weekly target days.</p>`)}${card('Weekly performance',`<div class="weekly-bars">${Array.from({length:7},(_,i)=>{const day=addDays(weekStart(selected),i),done=data.tasks.filter(r=>r.date===day&&r.done).length,habits=data.habitLogs.filter(r=>r.date===day).length;return `<div><span>${labelDate(day)}</span><strong>${done} tasks · ${habits} habits</strong></div>`}).join('')}</div>`)}${card('Goal progress',data.goals.length?data.goals.map(g=>`<div class="goal-entry">${ring(g.target?goalValue(g)/g.target*100:0,g.title)}<span>${escapeHTML(g.title)}</span></div>`).join(''):empty('goals'))}${card('Expense categories',total?Object.entries(Object.groupBy?Object.groupBy(expenses,r=>r.category||'Other'):expenses.reduce((a,r)=>{(a[r.category||'Other']??=[]).push(r);return a},{})).map(([k,v])=>`<div class="report-bar"><span>${escapeHTML(k)} · ${money(v.reduce((a,r)=>a+r.amount,0))}</span><div><i style="width:${Math.round(v.reduce((a,r)=>a+r.amount,0)/total*100)}%"></i></div></div>`).join(''):empty('transactions'))}</div><p class="disclaimer">Reports reflect records entered in this browser. Family time distribution counts scheduled entries by category; it does not measure hours spent. Progress is based on completed entries and logged habit days.</p>`}
function preference(k,title,opts){return `<label class="field">${title}<select data-setting="${k}">${opts.map(([v,t])=>`<option value="${v}" ${data.settings[k]===v?'selected':''}>${t}</option>`).join('')}</select></label>`}
function settings(){return `<div class="two-col">${card('Make it feel like yours',`<label class="field">Planner name<input data-setting="name" maxlength="45" value="${escapeHTML(data.settings.name)}"></label><h3>Color themes</h3><div class="theme-choices">${[['mint','Sea glass'],['peach','Apricot'],['lilac','Lavender'],['blue','Bluebell'],['custom','Your color']].map(([k,l])=>`<button class="theme-choice ${data.settings.theme===k?'selected':''}" data-theme="${k}" aria-pressed="${data.settings.theme===k}"><span class="theme-swatch ${k}"></span>${l}</button>`).join('')}</div><label class="field">Pick any accent color<input type="color" data-setting="customColor" value="${data.settings.customColor}"></label><div class="prefs">${preference('font','Font',[['system','Modern'],['serif','Soft serif'],['rounded','Rounded']])}${preference('density','Spacing',[['compact','Compact'],['comfortable','Comfortable'],['spacious','Spacious']])}${preference('cards','Cards',[['soft','Soft'],['outlined','Outlined']])}${preference('contrast','Readability',[['normal','Standard'],['high','Higher contrast']])}${preference('currency','Currency display',[['USD','USD'],['GBP','GBP'],['EUR','EUR'],['CAD','CAD'],['AUD','AUD'],['PKR','PKR']])}</div><label class="field">Monthly budget (${escapeHTML(data.settings.currency)})<input type="number" min="0" step="0.01" data-setting="monthlyBudget" value="${data.settings.monthlyBudget/100}"></label><button class="button ghost" data-reset-appearance>Restore default appearance</button>`)}${card('Your data, your hands',`<p>Keep a copy of your plans before you clear browser data or change devices.</p><div class="settings-actions"><button class="button primary" data-backup>Download JSON backup</button><button class="button ghost" data-import>Import backup</button><button class="button ghost" data-print>Print this page</button><button class="button danger-button" data-clear>Clear all records</button>${DEMO?'<button class="button ghost" data-reset-demo>Reset sample data</button>':''}</div><p class="disclaimer">Offline when opened as local files; after first successful online visit, HTTPS installations use a service worker cache where supported. No account, automatic syncing or push reminders.</p>`)}</div>`}

function recordCard(kind,title,summary){return card(title,button(kind)+list(kind,data[kind],r=>`<strong>${escapeHTML(r.title)}</strong><small>${escapeHTML(summary(r))}</small>`))}
function healthView(){return `<div class="two-col">${recordCard('medical','Appointments & health notes',r=>`${r.date?labelDate(r.date):''} · ${r.person||''} · ${r.provider||''} · ${r.detail||''}`)}${recordCard('medications','Medication reference',r=>`${r.person||''} · ${r.dose||''} · ${r.schedule||''} · refill ${r.refill?labelDate(r.refill):'not set'}`)}</div><p class="disclaimer">Reference notes only. Confirm medication directions with a professional. Avoid storing sensitive IDs; browser storage is not encrypted by this planner.</p>`}
function recipesView(){return `<div class="two-col">${card('Recipe library',button('recipes')+list('recipes',data.recipes,r=>`<strong>${escapeHTML(r.title)}</strong><small>${escapeHTML(r.category)} · ${r.minutes||0} minutes</small><p>${escapeHTML(r.ingredients||'').replaceAll('\n',' · ')}</p><button class="button ghost" data-ingredients="${escapeHTML(r.id)}">Add ingredients to groceries</button>`))}${card('Shopping list',button('groceries')+list('groceries',data.groceries,r=>check('groceries',r,r.title,r.category)))}</div>`}
function travelView(){return `<div class="two-col">${recordCard('trips','Trips & celebrations',r=>`${labelDate(r.date)} · ${r.destination||''} · ${r.note||''}`)}${card('Packing checklist',button('packing')+list('packing',data.packing,r=>check('packing',r,r.title,`${r.trip||'General'} · ${r.person||''}`)))}</div>`}
function memoriesView(){return `<div class="two-col">${recordCard('memories','Milestones & memories',r=>`${labelDate(r.date)} · ${r.person||''} · ${r.note||''}`)}${recordCard('traditions','Family traditions',r=>`${r.date?labelDate(r.date):'Any day'} · ${r.note||''}`)}</div><p class="disclaimer">Text keepsakes only. Photos and file attachments are not stored in the planner.</p>`}
function rewardsView(){return `${card('Kids rewards',button('rewards')+list('rewards',data.rewards,r=>`<div class="goal-entry">${ring(r.target?r.earned/r.target*100:0,r.title)}<span><strong>${escapeHTML(r.person)} · ${escapeHTML(r.title)}</strong><small>${r.earned} of ${r.target} points · ${escapeHTML(r.note)}</small><button class="button ghost" data-reward="${escapeHTML(r.id)}">+ 1 point</button></span></div>`))}<p class="disclaimer">Points are added manually by a family member. Rewards are for motivation, not a payment system.</p>`}
function searchPage(){const q=search.trim().toLocaleLowerCase();if(!q)return'';let matches=[];for(const k of kinds.filter(k=>k!=='habitLogs'&&k!=='billPayments'))for(const r of data[k])if(Object.values(r).some(v=>typeof v==='string'&&v.toLocaleLowerCase().includes(q)))matches.push({k,r});return `<div class="search-results"><h2>Search results · ${matches.length}</h2>${matches.slice(0,100).map(({k,r})=>`<article class="entry"><div class="entry-main"><strong>${escapeHTML(r.title||r.name||r.meal)}</strong><small>${k} ${r.date?'· '+labelDate(r.date):''}</small></div>${actions(k,r)}</article>`).join('')||'<p>No matching entries yet.</p>'}${matches.length>100?'<p>Showing first 100. Refine your search.</p>':''}</div>`}
function render(){const main=$('#main');main.innerHTML=`<div class="global-tools"><label for="globalSearch">Search all planner entries</label><input id="globalSearch" type="search" placeholder="Search plans, names, notes…" value="${escapeHTML(search)}"><button class="button ghost" data-print>Print page</button></div>${search.trim()?searchPage():header()+({dashboard,planner,calendar,family,meals,lists:listsView,money:moneyView,growth,wellness,home,reports,health:healthView,recipes:recipesView,travel:travelView,memories:memoriesView,rewards:rewardsView,settings})[view]()}`;document.querySelectorAll('[data-view]').forEach(b=>{const active=b.dataset.view===view;b.classList.toggle('active',active);b.setAttribute('aria-current',active?'page':'false')})}
function formOpen(k,rid='',date=''){const r=data[k].find(v=>v.id===rid)||{};modal={k,rid};$('#dialogTitle').textContent=(rid?'Edit ':'Add ')+(({'kids':'kids activity',school:'school item',care:'self-care entry',maintenance:'maintenance job',documents:'document reference'})[k]||k.slice(0,-1));$('#formFields').innerHTML=fields[k].map(([key,label,type,required])=>{const v=r[key]??(type==='date'?date||today():type==='check'?false:'');let input;if(type==='textarea')input=`<textarea name="${key}" maxlength="2000">${escapeHTML(v)}</textarea>`;else if(type.startsWith('select:'))input=`<select name="${key}">${type.slice(7).split('|').map(o=>`<option ${v===o?'selected':''}>${escapeHTML(o)}</option>`).join('')}</select>`;else if(type==='goal')input=`<select name="${key}"><option value="">General savings</option>${data.goals.map(g=>`<option value="${escapeHTML(g.id)}" ${v===g.id?'selected':''}>${escapeHTML(g.title)}</option>`).join('')}</select>`;else if(type==='check')input=`<input name="${key}" type="checkbox" ${v?'checked':''}>`;else input=`<input name="${key}" type="${type==='money'||['quantity','minutes','days'].includes(type)?'number':type}" ${type==='money'?'min="0" step="0.01"':(['quantity','minutes','days'].includes(type)?'min="0" step="1"':'maxlength="120"')} ${type==='days'?'max="7"':''} value="${escapeHTML(type==='money'&&r[key]!=null?v/100:v)}" ${required?'required':''}>`;return `<label class="field">${escapeHTML(label)}${input}</label>`}).join('');previousFocus=document.activeElement;dialog.showModal();$('#formFields').querySelector('input,textarea,select')?.focus()}
function download(name,content){const url=URL.createObjectURL(new Blob([content],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('#closeDialog').onclick=$('#cancelDialog').onclick=()=>dialog.close();
dialog.addEventListener('close',()=>{const target=previousFocus;previousFocus=null;setTimeout(()=>{if(target?.isConnected)target.focus();else document.querySelector('[data-view].active')?.focus()},0)});
$('#recordForm').addEventListener('submit',e=>{e.preventDefault();if(!modal)return;const{k,rid}=modal,old=data[k].find(r=>r.id===rid),r={id:rid||id()};for(const [key,,type,required] of fields[k]){let value=type==='check'?e.currentTarget.elements[key].checked:e.currentTarget.elements[key].value.trim();if(required&&(value===''||value===null))return alert('Fill in all required fields.');if(type==='date'&&value&&!dateOK(value))return alert('Enter a valid date.');if(type==='money'){value=cents(value);if(!Number.isSafeInteger(value)||value<0||value>100000000000)return alert('Enter a valid amount.')}if(['quantity','minutes','days'].includes(type)){value=value===''?0:Number(value);if(!Number.isSafeInteger(value)||value<0||value>100000000000||type==='days'&&value>7)return alert('Enter a valid whole number.')}r[key]=value}if(toggleKinds.has(k))r[k==='bills'?'paid':'done']=old?.[k==='bills'?'paid':'done']||false;if(rid)data[k][data[k].findIndex(x=>x.id===rid)]=r;else data[k].push(r);dialog.close();save();render()});
app.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.view){view=t.dataset.view;search='';render();return}if(t.dataset.ingredients){const r=data.recipes.find(x=>x.id===t.dataset.ingredients);if(r){let count=0;for(const line of (r.ingredients||'').split('\n').map(x=>x.trim()).filter(Boolean)){if(!data.groceries.some(x=>x.title.toLowerCase()===line.toLowerCase()&&!x.done)){data.groceries.push({id:id(),title:line,category:r.title,done:false});count++}}save();render();alert(count+' ingredient(s) added to groceries.')}return}if(t.dataset.reward){const r=data.rewards.find(x=>x.id===t.dataset.reward);if(r){r.earned=Math.min(r.target,r.earned+1);save();render()}return}if(t.dataset.add){formOpen(t.dataset.add,'',t.dataset.date||'');return}if(t.dataset.edit){const [k,rid]=t.dataset.edit.split(':');formOpen(k,rid);return}if(t.dataset.delete){const [k,rid]=t.dataset.delete.split(':');if(confirm('Delete this entry?')){data[k]=data[k].filter(r=>r.id!==rid);if(k==='habits')data.habitLogs=data.habitLogs.filter(r=>r.habitId!==rid);if(k==='bills')data.billPayments=data.billPayments.filter(r=>r.billId!==rid);if(k==='goals')for(const s of data.savings)if(s.goalId===rid)s.goalId='';save();render()}return}if(t.dataset.habit){const habitId=t.dataset.habit,index=data.habitLogs.findIndex(r=>r.habitId===habitId&&r.date===today());if(index<0)data.habitLogs.push({id:id(),habitId,date:today()});else data.habitLogs.splice(index,1);save();render();return}if(t.dataset.mode){mode=t.dataset.mode;render();return}if(t.dataset.chartRange){chartPeriod=Number(t.dataset.chartRange);render();return}if(t.dataset.offset){setSelected(Number(t.dataset.offset));return}if(t.dataset.shiftMonth){shiftMonth(Number(t.dataset.shiftMonth));return}if(t.hasAttribute('data-today')){selected=today();render();return}if(t.dataset.theme){data.settings.theme=t.dataset.theme;apply();save();render();return}if(t.hasAttribute('data-reset-appearance')){data.settings={...prefs(),name:data.settings.name,currency:data.settings.currency,monthlyBudget:data.settings.monthlyBudget};apply();save();render();return}if(t.hasAttribute('data-print')){window.print();return}if(t.hasAttribute('data-backup')){download('hearth-haven-backup-'+today()+'.json',JSON.stringify(data,null,2));return}if(t.hasAttribute('data-import')){$('#backupInput').click();return}if(t.hasAttribute('data-clear')&&confirm('Delete all planner entries? Download a backup first if you need them.')){data=blank();selected=today();save();render();return}if(t.hasAttribute('data-reset-demo')&&confirm('Replace demo edits with sample entries?')){data=sample();save();render()}});
app.addEventListener('change',e=>{const t=e.target;if(t.dataset.check){const[k,rid]=t.dataset.check.split(':'),r=data[k].find(x=>x.id===rid);if(r){if(k==='bills'&&r.cycle==='monthly'){const m=selected.slice(0,7),i=data.billPayments.findIndex(p=>p.billId===rid&&p.month===m);if(t.checked&&i<0)data.billPayments.push({id:id(),billId:rid,month:m});else if(!t.checked&&i>=0)data.billPayments.splice(i,1)}else r[k==='bills'?'paid':'done']=t.checked;save();render()}return}if(!t.dataset.setting)return;const k=t.dataset.setting;let v=t.value;if(k==='monthlyBudget'){v=cents(v);if(!Number.isSafeInteger(v)||v<0||v>100000000000){alert('Enter a valid nonnegative budget.');render();return}}if(k==='name')v=v.trim().slice(0,45)||'Our family';data.settings[k]=v;if(k==='customColor')data.settings.theme='custom';apply();save();render()});
let searchTimer;app.addEventListener('input',e=>{if(e.target.id!=='globalSearch')return;search=e.target.value;const caret=e.target.selectionStart;clearTimeout(searchTimer);searchTimer=setTimeout(()=>{render();$('#globalSearch').focus();$('#globalSearch').setSelectionRange(caret,caret)},130)});
$('#backupInput').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>10000000)throw Error('Backup must be smaller than 10 MB.');const raw=JSON.parse(await file.text());if(!valid(raw))throw Error('Not a valid Hearth Haven backup.');if(confirm('Replace all current entries with this backup?')){data=migrate(raw);save();apply();render();alert('Backup restored.')}}catch(err){alert('Import failed: '+err.message)}finally{e.target.value=''}});
shell();if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
